# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={},
        ),
        migrations.RemoveField(
            model_name='link',
            name='language',
        ),
        migrations.RemoveField(
            model_name='link',
            name='style',
        ),
        migrations.AddField(
            model_name='link',
            name='link',
            field=models.CharField(default=b'python', max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
